version: '3'

services:
  magicmirror:
    container_name: mm
    image: karsten13/magicmirror:latest
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
    privileged: true # avoids dbus errors in logs
    environment:
      DISPLAY: unix:0.0
    shm_size: "128mb"
    restart: unless-stopped
    # you have to substitute below address and port parameters with your own values:
    command: "node clientonly --address 192.168.0.143 --port 8080"

