version: '3'

services:
  magicmirror:
    container_name: magicmirror
    image: karsten13/magicmirror:latest
    environment:
      OPENWEATHER_API_KEY: ${OPENWEATHER_API_KEY}
    ports:
      - "8080:8080"
    volumes:
      - ../mounts/config:/opt/magic_mirror/config
      - ../mounts/modules:/opt/magic_mirror/modules
      - ../mounts/css:/opt/magic_mirror/css
    restart: unless-stopped
    command:
      - npm
      - run
      - server

  mmpm:
    container_name: mmpm
    image: karsten13/mmpm:latest
    depends_on:
      - magicmirror
    ports:
      - "7890:7890"
      - "7891:7891"
      - "6789:6789"
      - "8907:8907"
    volumes:
      - ../mounts/modules:/home/node/MagicMirror/modules
      - ../mounts/config:/home/node/MagicMirror/config
      - ../mounts/css:/home/node/MagicMirror/css
      - ../mounts/mmpm-config:/home/node/.config/mmpm
    restart: unless-stopped

